{% set name = "pytest-base-url" %}
{% set version = "1.4.2" %}
{% set hash = "7f1f32e08c2ee751e59e7f5880235b46e83496adc5cba5a01ca218c6fe81333d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - pytest >=2.7.3
    - requests >=2.9

  run:
    - python
    - setuptools
    - pytest >=2.7.3
    - requests >=2.9

test:
  imports:
    - pytest_base_url

about:
  home: https://github.com/pytest-dev/pytest-base-url
  license: MPL 2.0
  license_family: OTHER
  license_file: LICENSE
  summary: pytest plugin for URL based testing

extra:
  recipe-maintainers:
    - birdsarah
    - davehunt
