{% set name = "pytest-base-url" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-base-url-{{ version }}.tar.gz
  sha256: e1e88a4fd221941572ccdcf3bf6c051392d2f8b6cef3e0bc7da95abec4b5346e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.7
    - pytest >=3.0.0,<8.0.0
    - requests >=2.9

test:
  imports:
    - pytest_base_url
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytest-dev/pytest-base-url
  summary: pytest plugin for URL based testing
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - birdsarah
    - davehunt
    - nicoddemus
