{% set name = "pytest-base-url" %}
{% set version = "1.4.1" %}
{% set hash_type = "sha256" %}
{% set hash = "7425e8163345494ac7f544e99c6f3e5a08f4228bee5e26013b98c462a4d31f6e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - pytest >=2.7.3
    - requests >=2.9

  run:
    - python
    - setuptools
    - pytest >=2.7.3
    - requests >=2.9

test:
  imports:
    - pytest_base_url

about:
  home: https://github.com/pytest-dev/pytest-base-url
  license: MPL 2.0
  license_family: OTHER
  license_file: LICENSE
  summary: 'pytest plugin for URL based testing'

extra:
  recipe-maintainers:
    - birdsarah
    - davehunt
    - nicoddemus
