travis:
  secure:
    BINSTAR_TOKEN: Hjn3NNGngFjJQOetrNy+1xzRL8i4eZYnWhY4ftVLSUDPdFMlmHoAvdFNRpckzjXUie0dg1D9KylCwxzIlN2vMZjbFXiLMZxxYEiJuZ5rHgwZrUhLiSaTJjq2MLxadU9xzpW6hW86AKY1yULwwd1LaU/YDGgtpeOTaNFYGHtkRYxWCs3y6VEn7+2I0xnbD4qM6MDZFKz4icxnSXMhnUeSWQqwcso2CHd4myadCDoa8PNz/Ud3sGFgNnnOkthJfvWVUJM7UvKa/S5MA4hyqmlFHEdu/awkWTQ10dwEKTwkGn+hFq/2KsU0VWKLgG6PFHZfOfiYFMiP3kRJPRTOiHKbqW+C6HCe/8q/JJItM6hQw7VeFhRgmKHFVfUfkBNMsg0YIaODYMw3mn317/ifGPiCUfwwOW3tMYHdoxoDtFrdo4ivq2XkgyIu4UNspFDgAxNn25vv19NyeZZiN94YvQJ6pKEEYWTmsYd/OBv6ZO4CAqaAPwZY2sReFIWmYerF1BrJbLbZMeQHkAb2ewL6bae0F5xYA/PyEQgegTNDmIk61KwGQms/Bj3uJZzrjnLk1m2FPeag4mkjcQ4oYRKkU0lqDbdo+5en6LtkmKPQSjrMbq1vZXwoT6wC7WCaWhPCrQL7KBB8t2OgKLw87ruaxvBpc7mSlgNKs4RH+9UxfMbM/9M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
