travis:
  secure:
    BINSTAR_TOKEN: PPUiz0n2yOIkbkmHt678QJ0Z3LfrulIkmcO9TNEaenmzu0WQJrFO5NnaODT6Tp1RReclRhTE5ApF8Nz+B9EAMthz0mglmeNYtmOPNiIENCNepfgI7bEUBHxheMB1/1DF4l1ebtmlc80PhOInAogflyYSoXk4l5lS0ONcX96zZJfxl7kabrzrov/4vwEHxNVd57/2TCwL4oa2qegapTnuZ6cGouJ9jkp03XcxeKhtEvKTwU24CPFmK8+OjoeERiPAe0Su/GDXYhIJ+RJtth0ZCD270hOBpM/F4RkwRGzSxxkz27bQsXfmw8nW5mO3oqzRKUQfVZ6m3XLJb5eVgaUS0WE8uXxXumPhdj+aXUMJ6LxchkI0oc7Va5q2poPfHRqaEzA/wOW36xbXeEYPfOxFMrWfHSh5s+S4bsPxSZl7n2aPS15OW8x0g3Z1Zx5I4nJbfBRN/qNKnNiNidd5jpT8+msE3s9XWJDEheomk9MZpQYR5tPFrs+8YJloDJQRPl6OujMQJiQlvbWJFe2X6xPP6UtObfU+YKiL0ABeY8ND4oXb+YGp0FjPvrgGYwDRDW+1GzGBS1wLps3r0lBVCgiFjyjFJb8S4BtBRRPObHvmbpD4vHTAg5NOe0dKaJwfm5ulQ45c1ImGJ7CL+ZLVpD/MrZvrZItOd9UEvisVn8tVEEs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
